export const SHOP_SEED_PRODUCTS = [
  {
    title: "Pokémon TCG: Scarlet & Violet — Prismatic Evolutions Booster Box",
    slug: "sv-prismatic-evolutions-booster-box",
    description: "36-pack booster box from the highly sought-after Prismatic Evolutions set. Each pack contains 10 cards with stunning alternate art possibilities featuring all Eeveelutions.",
    category: "sealed",
    condition: "Factory Sealed",
    product_type: "Booster Box",
    source_type: "distributor",
    msrp_price: 143.64,
    market_price: 289.99,
    member_price: 219.99,
    premium_member_price: 199.99,
    public_price: 259.99,
    cost_basis: 95.00,
    inventory_count: 12,
    max_qty_per_member: 1,
    max_qty_per_household: 2,
    requires_membership: false,
    premium_only: false,
    early_access_enabled: true,
    early_access_minutes: 30,
    status: "active",
    images: JSON.stringify([
      "https://images.pokemontcg.io/sv8p/logo.png",
    ]),
  },
  {
    title: "Pokémon TCG: Sword & Shield — Crown Zenith Elite Trainer Box",
    slug: "swsh-crown-zenith-etb",
    description: "Premium Elite Trainer Box featuring the Crown Zenith expansion. Includes 10 booster packs, dice, sleeves, energy cards, and collector's storage box.",
    category: "sealed",
    condition: "Factory Sealed",
    product_type: "Elite Trainer Box",
    source_type: "distributor",
    msrp_price: 49.99,
    market_price: 89.99,
    member_price: 64.99,
    premium_member_price: 59.99,
    public_price: 74.99,
    cost_basis: 30.00,
    inventory_count: 25,
    max_qty_per_member: 2,
    max_qty_per_household: 3,
    status: "active",
    images: JSON.stringify([
      "https://images.pokemontcg.io/swsh12pt5/logo.png",
    ]),
  },
  {
    title: "Charizard ex — Obsidian Flames 215/197 Special Art Rare",
    slug: "charizard-ex-obsidian-flames-sar",
    description: "Charizard ex Special Art Rare from the Obsidian Flames expansion. Near Mint condition with clean centering and sharp corners.",
    category: "singles",
    condition: "Near Mint",
    product_type: "Single Card",
    source_type: "personal_collection",
    msrp_price: null,
    market_price: 149.99,
    member_price: 124.99,
    premium_member_price: 114.99,
    public_price: 139.99,
    cost_basis: 45.00,
    inventory_count: 1,
    max_qty_per_member: 1,
    max_qty_per_household: 1,
    status: "active",
    images: JSON.stringify([
      "https://images.pokemontcg.io/sv3/215_hires.png",
    ]),
  },
  {
    title: "Umbreon VMAX — Evolving Skies 215/203 Alternate Art Secret Rare",
    slug: "umbreon-vmax-evolving-skies-alt-art",
    description: "The iconic Umbreon VMAX Alternate Art from Evolving Skies. One of the most sought-after modern Pokémon cards. Excellent condition.",
    category: "singles",
    condition: "Near Mint",
    product_type: "Single Card",
    source_type: "member_trade_in",
    msrp_price: null,
    market_price: 329.99,
    member_price: 279.99,
    premium_member_price: 259.99,
    public_price: 309.99,
    cost_basis: 150.00,
    inventory_count: 1,
    max_qty_per_member: 1,
    max_qty_per_household: 1,
    requires_membership: true,
    status: "active",
    images: JSON.stringify([
      "https://images.pokemontcg.io/swsh7/215_hires.png",
    ]),
  },
  {
    title: "Charizard Base Set 4/102 — PSA 10 Gem Mint",
    slug: "charizard-base-set-psa-10",
    description: "Graded PSA 10 Gem Mint 1st Edition Charizard from the original Base Set. One of the most iconic cards in Pokémon history. Includes PSA case and certificate.",
    category: "graded",
    condition: "PSA 10 Gem Mint",
    product_type: "Graded Card",
    source_type: "personal_collection",
    msrp_price: null,
    market_price: 12999.99,
    member_price: 11499.99,
    premium_member_price: 10999.99,
    public_price: 12499.99,
    cost_basis: 5000.00,
    inventory_count: 1,
    max_qty_per_member: 1,
    max_qty_per_household: 1,
    premium_only: true,
    requires_membership: true,
    status: "active",
    images: JSON.stringify([
      "https://images.pokemontcg.io/base1/4_hires.png",
    ]),
  },
  {
    title: "Poké Trade Mystery Pack — Standard Edition",
    slug: "mystery-pack-standard",
    description: "Our curated mystery pack includes 5 hand-picked cards from various sets. Guaranteed at least 1 holo or better! Great for new collectors or gift-giving.",
    category: "mystery",
    condition: "Mixed",
    product_type: "Mystery Pack",
    source_type: "other",
    msrp_price: null,
    market_price: 24.99,
    member_price: 14.99,
    premium_member_price: 12.99,
    public_price: 19.99,
    cost_basis: 5.00,
    inventory_count: 50,
    max_qty_per_member: 3,
    max_qty_per_household: 5,
    status: "active",
    images: JSON.stringify([]),
  },
  {
    title: "Poké Trade Mystery Pack — Premium Hits Edition",
    slug: "mystery-pack-premium-hits",
    description: "Premium mystery pack with 3 guaranteed ultra rare or better pulls! Each pack is curated from our verified inventory with cards valued $10+.",
    category: "mystery",
    condition: "Near Mint",
    product_type: "Mystery Pack",
    source_type: "other",
    msrp_price: null,
    market_price: 59.99,
    member_price: 44.99,
    premium_member_price: 39.99,
    public_price: 54.99,
    cost_basis: 20.00,
    inventory_count: 20,
    max_qty_per_member: 2,
    max_qty_per_household: 3,
    requires_membership: true,
    status: "active",
    images: JSON.stringify([]),
  },
  {
    title: "Maria's Personal Collection — Vintage Holo Lot (5 Cards)",
    slug: "personal-collection-vintage-holo-lot",
    description: "From the owner's personal collection: 5 hand-selected vintage holographic cards from the WOTC era (Base Set through Neo). Each lot is unique and photographed individually.",
    category: "personal_collection",
    condition: "Light Play to Near Mint",
    product_type: "Card Lot",
    source_type: "personal_collection",
    msrp_price: null,
    market_price: 199.99,
    member_price: 149.99,
    premium_member_price: 129.99,
    public_price: 179.99,
    cost_basis: 50.00,
    inventory_count: 3,
    max_qty_per_member: 1,
    max_qty_per_household: 1,
    premium_only: true,
    requires_membership: true,
    status: "active",
    images: JSON.stringify([]),
  },
  {
    title: "Pokémon TCG: Scarlet & Violet — Surging Sparks Booster Box",
    slug: "sv-surging-sparks-booster-box-drop",
    description: "LIMITED DROP: Surging Sparks booster box at below market pricing! 36 packs per box. Early access for premium members.",
    category: "sealed",
    condition: "Factory Sealed",
    product_type: "Booster Box",
    source_type: "distributor",
    msrp_price: 143.64,
    market_price: 159.99,
    member_price: 129.99,
    premium_member_price: 119.99,
    public_price: 144.99,
    cost_basis: 90.00,
    inventory_count: 8,
    max_qty_per_member: 1,
    max_qty_per_household: 1,
    early_access_enabled: true,
    early_access_minutes: 30,
    drop_start_at: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(), // 7 days from now
    public_start_at: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000 + 30 * 60 * 1000).toISOString(),
    status: "scheduled",
    images: JSON.stringify([
      "https://images.pokemontcg.io/sv7/logo.png",
    ]),
  },
];
